# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FineFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=20)),
                ('userId', models.CharField(max_length=20)),
                ('profileName', models.CharField(max_length=20)),
                ('helpfulness', models.IntegerField(blank=True, null=True)),
                ('review', models.FloatField(blank=True, default=None, null=True)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('review_summary', models.TextField()),
                ('review_text', models.TextField()),
            ],
        ),
    ]
